### ISSUE TITLE
Add support for remote triplestore

### ISSUE THREAD

**Issue by awoods** [vivo-community/scholars-discovery#190]
In addition to the SDB and TDB [Triplestore](https://github.com/vivo-community/scholars-discovery/blob/master/src/main/java/edu/tamu/scholars/middleware/service/Triplestore.java) implementations, it would be valuable to support remote (SPARQL over HTTP) triplestores.

Although such a configuration will likely have not have the same performance advantages of TDB, it will enable `scholars-discovery` users to connect to all VIVO installations, not just those that use SDB or TDB.
See: https://wiki.lyrasis.org/display/VIVODOC111x/SPARQL+Query+API

**Comment by wwelling** [comment]
I recommend implanting utilizing this existing service, https://github.com/vivo-community/scholars-discovery/blob/master/src/main/java/edu/tamu/scholars/middleware/service/VivoService.java

**Comment by awoods** [comment]
Nice. Is there documentation for enabling the VivoService for indexing?

**Comment by wwelling** [comment]
The `VivoService` is not currently integrated in the indexing. It can be configured in [application.yml](https://github.com/vivo-community/scholars-discovery/blob/master/src/main/resources/application.yml#L62) and `@Autowired` for use within beans. Unfortunately, there is no documentation for this service. Clearly a weak point.

For a RemoteTriplestore, I would assume it would not want to be coupled or semantically implicating only VIVO's APIs. Therefor, a new configurations should probably be created and the RemoteTriplestore implementation can be built referencing techniques, or not, from `VivoService`. The configuration would make sense to be additions to the existing triplestore config.

```
triplestore:
    type: edu.tamu.scholars.middleware.service.RemoteTriplestore
    directory: N/A
    datasourceUrl: N/A
    remoteUrl: [use this or possibly reuse datasourceUrl, could refactor it as well]
    username: [if authentication required]
    password: [if authentication required]
```

**Comment by wwelling** [comment]
An alternative to trying to implement a remote triplestore via SPARQL over HTTP, a `Harvester` can be implemented similar to [LocalTriplestoreHarvester](https://github.com/vivo-community/scholars-discovery/blob/master/src/main/java/edu/tamu/scholars/middleware/discovery/service/jena/LocalTriplestoreHarvester.java). `LocalTriplestoreHarvester` is somewhat a semantically incorrect name. It autowires whichever triplestore is configured to harvest data. That triplestore can be a TDB or SDB. TDB can be local directory or mounted directory. SDB can be local database or remote database.

Implementing a `RemoteSPARQLHarvester` would pretty much neglect the triplestore. This would most likely be the easier approach. Implementing a [Triplestore](https://github.com/vivo-community/scholars-discovery/blob/master/src/main/java/edu/tamu/scholars/middleware/service/Triplestore.java) would require 'piping' SPARQL over HTTP responses through a Dataset. Not sure that is feasible or even makes sense to do.

Something like this would make sense configuring:
```
  harvesters:
  - type: edu.tamu.scholars.middleware.discovery.service.jena.RemoteSPARQLHarvester
    documentTypes:
    - edu.tamu.scholars.middleware.discovery.model.Collection
    - edu.tamu.scholars.middleware.discovery.model.Concept
    - edu.tamu.scholars.middleware.discovery.model.Document
    - edu.tamu.scholars.middleware.discovery.model.Organization
    - edu.tamu.scholars.middleware.discovery.model.Person
    - edu.tamu.scholars.middleware.discovery.model.Process
    - edu.tamu.scholars.middleware.discovery.model.Relationship

remote-sparql:
  url:
  username:
  password:
```
